# Joint configuration for joint_state_publisher_gui

joint_state_publisher:
  ros__parameters:
    # Joint names and default positions
    zeros:
      Revolute_5: 0.0
      Revolute_6: 0.0
      Revolute_8: 0.0
      Revolute_9: 0.0

    # Joints to publish
    source_list:
      - Revolute_5
      - Revolute_6
      - Revolute_8
      - Revolute_9